apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: security-champion-admin
  name:  dependabotnotifier
  namespace: security-champion-admin
spec:
  image: {{ image }}
  schedule: {{ schedule }}
  ttlSecondsAfterFinished: 300
  resources:
    requests:
      cpu: "100m"
      memory: 300Mi
  envFrom:
    - secret: dependabotnotifier
