apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: security-champion-admin
  name:  dependabotnotifier
  namespace: security-champion-admin
spec:
  image: {{ image }}
  schedule: {{ schedule }}
  ttlSecondsAfterFinished: 300
  resources:
    requests:
      cpu: "100m"
      memory: 300Mi
  envFrom:
    - secret: github-security-slack-notifier
  accessPolicy:
    outbound:
      external:
        - host: apiserver.prod-gcp.nav.cloud.nais.io
        - host: api.github.com
        - host: slack.com
      rules:
        - application: nais-api-cluster
          namespace: nais-system

