name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
jobs:
  build:
    name: Build all the things
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      RUNNER_IMG: "gcr.io/distroless/static-debian11"
      RUNNERIMG_IDENTITY: "keyless@distroless.iam.gserviceaccount.com"
      RUNNERIMG_ISSUER: "https://accounts.google.com"
    outputs:
      tag: "${{ fromJSON(steps.docker-build-push.outputs.metadata) }}"
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # ratchet:actions/checkout@v3
      - name: Install cosign
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.1.1'
      - name: Verify runner image
        run: cosign verify --certificate-identity ${{ env.RUNNERIMG_IDENTITY }} --certificate-oidc-issuer ${{ env.RUNNERIMG_ISSUER }} ${{ env.RUNNER_IMG }}
      - uses: nais/docker-build-push@c1d05d5a796be7b24d59a2e76851acdcdbcaff7a # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        name: Build and push Docker image
        with:
          team: security-champion-admin
          push_image: false
          pull: true
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
